//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITVidpra_AgriCulture_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Taluka
    {
        public int T_No { get; set; }
        public string T_Name { get; set; }
        public string Pin_Code { get; set; }
        public string Tehashil { get; set; }
        public Nullable<int> D_No { get; set; }
        public string D_Name { get; set; }
    
        public virtual tbl_District tbl_District { get; set; }
    }
}
