//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITVidpra_AgriCulture_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Crops
    {
        internal int id;

        public int C_No { get; set; }
        public string C_Name { get; set; }
        public string C_Type { get; set; }
        public string C_Duration { get; set; }
        public string C_Description { get; set; }
    }
}
